name = "toolweb"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tool-media"

[vars]
PUBLIC_SUPABASE_URL = "https://eknmuaffpvkiwylrybql.supabase.co"
PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY = "sb_publishable_qm6XxPJLZ3w2Mn5xFkMDUA_Rkpoy7iU"
PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_51SZzHLRsGSph5NYi3EdzzaAlB3scpY0jgYAIv6O3Q34D71FuOzO4G8p6577SsiqHja0xw8mMasQETwMH1DLU91d000l1PqUxyX"
R2_PUBLIC_URL = "https://media.tool.nyc"
PUBLIC_SITE_URL = "https://tool.nyc"
